# Generated by Django 6.0.1 on 2026-01-11 09:12

import django.core.validators
import django.db.models.deletion
import tickets.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bug', 'Bug'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Testing', 'Testing'), ('Error', 'Error')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(25)], verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('estimated_time', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('status', models.CharField(choices=[('ToDo', 'ToDo'), ('InProgress', 'InProgress'), ('Done', 'Done')], db_default='ToDo', default='ToDo', max_length=10)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_default='Medium', default='Medium', max_length=6)),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True, validators=[tickets.models.validate_not_past_date])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='tickets.category')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
